<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="4053" started-at="2022-01-30T13:24:00Z" finished-at="2022-01-30T13:24:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="4053" started-at="2022-01-30T13:24:00Z" finished-at="2022-01-30T13:24:04Z">
      <class name="org.testing.testScript.TC2">
        <test-method status="PASS" signature="testCase2()[pri:0, instance:org.testing.testScript.TC2@29ee9faa]" name="testCase2" duration-ms="750" started-at="2022-01-30T18:54:03Z" finished-at="2022-01-30T18:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
      </class> <!-- org.testing.testScript.TC2 -->
      <class name="org.testing.testScript.TC3">
        <test-method status="PASS" signature="testCase3()[pri:0, instance:org.testing.testScript.TC3@c038203]" name="testCase3" duration-ms="54" started-at="2022-01-30T18:54:04Z" finished-at="2022-01-30T18:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
      </class> <!-- org.testing.testScript.TC3 -->
      <class name="org.testing.testScript.TC1">
        <test-method status="FAIL" signature="testCase1()[pri:0, instance:org.testing.testScript.TC1@724af044]" name="testCase1" duration-ms="3064" started-at="2022-01-30T18:54:00Z" finished-at="2022-01-30T18:54:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ts match expected [200] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ts match expected [200] but found [201]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testing.Responcevalidation.ResponceValidation.statusCodevalidation(ResponceValidation.java:20)
	at org.testing.testScript.TC1.testCase1(TC1.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
      </class> <!-- org.testing.testScript.TC1 -->
      <class name="org.testing.testScript.TC6">
        <test-method status="PASS" signature="testCase6()[pri:0, instance:org.testing.testScript.TC6@8bd1b6a]" name="testCase6" duration-ms="31" started-at="2022-01-30T18:54:04Z" finished-at="2022-01-30T18:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase6 -->
      </class> <!-- org.testing.testScript.TC6 -->
      <class name="org.testing.testScript.TC7">
        <test-method status="PASS" signature="testCase7()[pri:0, instance:org.testing.testScript.TC7@18be83e4]" name="testCase7" duration-ms="4" started-at="2022-01-30T18:54:04Z" finished-at="2022-01-30T18:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase7 -->
      </class> <!-- org.testing.testScript.TC7 -->
      <class name="org.testing.testScript.TC4">
        <test-method status="PASS" signature="testCase4()[pri:0, instance:org.testing.testScript.TC4@cc285f4]" name="testCase4" duration-ms="64" started-at="2022-01-30T18:54:04Z" finished-at="2022-01-30T18:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase4 -->
      </class> <!-- org.testing.testScript.TC4 -->
      <class name="org.testing.testScript.TC5">
        <test-method status="PASS" signature="testCase5()[pri:0, instance:org.testing.testScript.TC5@55f3ddb1]" name="testCase5" duration-ms="49" started-at="2022-01-30T18:54:04Z" finished-at="2022-01-30T18:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase5 -->
      </class> <!-- org.testing.testScript.TC5 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
